version: "3.8"
services:

  # Backing Services

  amazon-postgres:
    image: "postgres:16.1"
    container_name: "amazon-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - amazon

networks:
    amazon:
        name: amazon
        driver: bridge
