version: "3.8"
services:

  # Backing Services

  engineer-postgres:
    image: "postgres:14.4"
    container_name: "engineer-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

